class OECDepartments

  attr_accessor :dept_code, :file_name, :form_code, :eval_types, :ets_managed

  def initialize(dept_code, file_name, form_code, eval_types, ets_managed)
    @dept_code = dept_code
    @dept_name = file_name
    @form_code = form_code
    @eval_types = eval_types
    @ets_managed = ets_managed
  end

  DEPARTMENTS = [
      AFRICAM = new('AFRICAM', 'African American Studies', 'AFRICAM', %w(F G), true),
      AFRIKANS = new('AFRKANS', 'German', 'GERMAN', %w(F), true),
      AGR_CHM = new('AGR CHM', 'Plant Biology', 'PLANTBI', nil, true),
      AMERSTD = new('AMERSTD', 'Undergraduate and Interdisciplinary Studies', 'UGIS', %w(F G), true),
      ANTHRO = new('ANTHRO', 'Anthropology', 'ANTHRO', %w(F G), true),
      A_RESEC = new('A,RESEC', 'Agricultural and Resource Economics', 'A,RESEC', %w(F G), true),
      ASIANST = new('ASIANST', 'International and Area Studies', 'IAS', %w(F G), true),
      AST = new('AST', 'Engineering', 'ENGIN', nil, false),
      ASTRON = new('ASTRON', 'Astronomy', 'ASTRON', %w(F G), true),
      BIC = new('BIC', 'Undergraduate and Interdisciplinary Studies', 'BIC', %w(F G), true),
      BIO_ENG = new('BIO ENG', 'Bioengineering', 'BIO ENG', nil, false),
      CATALAN = new('CATALAN', 'Spanish and Portuguese', 'SPANISH', %w(LANG LECT SEMI WRIT), true),
      CHEM = new('CHEM', 'Chemistry', 'CHEM', %w(F G), true),
      CIV_ENG = new('CIV ENG', 'Civil and Environmental Engineering', 'CIV ENG', nil, false),
      COG_SCI = new('COG SCI', 'International and Area Studies', 'IAS', %w(F G), true),
      COLWRIT = new('COLWRIT', 'College Writing', 'COLWRIT', %w(F G), true),
      COM_LIT = new('COM LIT', 'Comparative Literature', 'COM LIT', %w(G), true),
      COMPBIO = new('COMPBIO', 'Graduate Division', 'COMPBIO', nil, true),
      COMPSCI = new('COMPSCI', 'Electrical Engineering and Computer Science', 'COMPSCI', nil, false),
      DATASCI = new('DATASCI', 'Information', 'DATASCI', nil, true),
      DES_INV = new('DES INV', 'Engineering', 'ENGIN', nil, false),
      DEV_ENG = new('DEV ENG', 'Civil and Environmental Engineering', 'CIV ENG', nil, false),
      DEV_STD = new('DEV STD', 'International and Area Studies', 'IAS', %w(F G), true),
      DEVP = new('DEVP', 'Development Practice', 'DEVP', nil, true),
      DUTCH = new('DUTCH', 'German', 'GERMAN', %w(F), true),
      ECON = new('ECON', 'Economics', 'ECON', %w(F G), true),
      EECS = new('EECS', 'Electrical Engineering and Computer Science', 'EL ENG', nil, false),
      EL_ENG = new('EL ENG', 'Electrical Engineering and Computer Science', 'EL ENG', nil, false),
      ENE_RES = new('ENE,RES', 'Energy and Resources Group', 'ENE,RES', %w(F G), true),
      ENGIN = new('ENGIN', 'Engineering', 'ENGIN', nil, false),
      ENVECON = new('ENVECON', 'Agricultural and Resource Economics', 'A,RESEC', %w(F G), true),
      ENV_SCI = new('ENV SCI',  'Environmental Science, Policy, and Management', 'ESPM', %w(F G), true),
      EPS = new('EPS', 'Earth and Planetary Science', 'EPS', %w(F G), true),
      ESPM = new('ESPM', 'Environmental Science, Policy, and Management', 'ESPM', %w(F G), true),
      ETH_STD = new('ETH STD', 'Ethnic Studies', 'ETH STD', %w(F G), true),
      FSSEM = new('FSSEM', 'Freshman and Sophomore Seminars', 'FSSEM', nil, true),
      GEOG = new('GEOG', 'Geography', 'GEOG', nil, true),
      GERMAN = new('GERMAN', 'German', 'GERMAN', %w(F), true),
      GLOBAL = new('GLOBAL', 'International and Area Studies', 'IAS', %w(F G), true),
      GPP = new('GPP', 'International and Area Studies', 'IAS', %w(F G), true),
      GSPDP = new('GSPDP', 'Graduate Division', 'LAN PRO', nil, true),
      GWS = new('GWS', 'Gender and Women\'s Studies', 'GWS', %w(F G), true),
      HMEDSCI = new('HMEDSCI', 'Public Health', 'PB HLTH', nil, false),
      IAS = new('IAS', 'International and Area Studies', 'IAS', %w(F G), true),
      ILA = new('ILA', 'Spanish and Portuguese', 'SPANISH', %w(LANG LECT SEMI WRIT), true),
      IND_ENG = new('IND ENG', 'Industrial Engineering and Operations Research', 'IND ENG', nil, false),
      INFO = new('INFO', 'Information', 'INFO', %w(F G), true),
      INTEGBI = new('INTEGBI', 'Integrative Biology', 'INTEGBI', %w(F G), true),
      ISF = new('ISF', 'Undergraduate and Interdisciplinary Studies', 'ISF', nil, true),
      JOURN = new('JOURN', 'Journalism', 'JOURN', nil, true),
      L_AND_S = new('L & S', 'Undergraduate and Interdisciplinary Studies', 'UGIS', %w(F G), true),
      LAN_PRO = new('LAN PRO', 'Graduate Division', 'LAN PRO', nil, true),
      LATAMST = new('LATAMST', 'Graduate Division', 'LAN PRO', nil, true),
      LEGALST = new('LEGALST', 'Law', nil, nil, false),
      LGBT = new('LGBT', 'Gender and Women\'s Studies', 'GWS', %w(F G), true),
      LINGUIS = new('LINGUIS', 'Linguistics', 'LINGUIS', %w(F G), true),
      MATH = new('MATH', 'Math', 'MATH', %w(F G), true),
      MAT_SCI = new('MAT SCI', 'Materials Science and Engineering', 'MAT SCI', nil, false),
      MCELLBI = new('MCELLBI', 'Molecular and Cell Biology', 'MCELLBI', %w(F G), true),
      MEC_ENG = new('MEC ENG', 'Mechanical Engineering', 'MEC ENG', nil, false),
      MEDIAST = new('MEDIAST', 'Undergraduate and Interdisciplinary Studies', 'UGIS', %w(F G), true),
      M_E_STU = new('M E STU', 'International and Area Studies', 'IAS', %w(F G), true),
      MUSIC = new('MUSIC', 'Music', 'MUSIC', %w(F G), true),
      NAT_RES = new('NAT RES', 'Natural Resources', 'NAT RES', nil, false),
      NEUROSC = new('NEUROSC', 'Helen Wills Neuroscience', 'NEUROSC', nil, false),
      NSE = new('NSE', 'Engineering', 'ENGIN', nil, false),
      NUC_ENG = new('NUC ENG', 'Nuclear Engineering', 'NUC ENG', nil, false),
      NUSCTX = new('NUSCTX', 'Nutritional Sciences and Toxicology', 'NUSCTX', nil, true),
      NWMEDIA = new('NWMEDIA', 'New Media', 'NWMEDIA', nil, true),
      PACS = new('PACS', 'International and Area Studies', 'IAS', %w(F G), true),
      PB_HLTH = new('PB HLTH', 'Public Health', 'PB HLTH', nil, false),
      PHYS_ED = new('PHYS ED', 'Physical Education', 'PHYS ED', %w(F G), true),
      PHYSICS = new('PHYSICS', 'Physics', 'PHYSICS', %w(F G), true),
      PLANTBI = new('PLANTBI', 'Plant Biology', 'PLANTBI', nil, true),
      POLECON = new('POLECON', 'International and Area Studies', 'IAS', %w(F G), true),
      POL_SCI = new('POL SCI', 'Political Science', 'POL SCI', %w(F G), true),
      PORTUG = new('PORTUG', 'Spanish and Portuguese', 'SPANISH', %w(LANG LECT SEMI WRIT), true),
      PSYCH = new('PSYCH', 'Psychology', 'PSYCH', nil, true),
      PUB_POL = new('PUB POL', 'Goldman School of Public Policy', 'PUB POL', nil, false),
      RELIGST = new('RELIGST', 'Undergraduate and Interdisciplinary Studies', 'UGIS', %w(F G), true),
      RHETOR = new('RHETOR', 'Rhetoric', 'RHETOR', %w(F G), true),
      SOC_WEL = new('SOC WEL', 'Social Welfare', 'SOC WEL', nil, false),
      SPANISH = new('SPANISH', 'Spanish and Portuguese', 'SPANISH', %w(LANG LECT SEMI WRIT), true),
      STAT = new('STAT', 'Statistics', 'STAT', %w(F G), true),
      THEATER = new('THEATER', 'Theater, Dance, and Performance', 'THEATER', %w(F G), true),
      UGIS = new('UGIS', 'Undergraduate and Interdisciplinary Studies', 'UGIS', %w(F G), true),
      YIDDISH = new('YIDDISH', 'German', 'GERMAN', %w(F), true)
  ]

end
